site_name: Introdução ao Revit
use_directory_urls: false

copyright: Copyright &copy; 2016 - 2021 Fernando Ferraz Ribeiro

theme:
  features:

    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  

site_url: "https://255ribeiro.github.io/Intro_Revit/"
repo_url: "https://github.com/255ribeiro/Intro_Revit/"
repo_name: "255ribeiro/Intro_Revit" 


nav:
  - Home: index.md
  - Editais das Avaliações: revit\EditaisDasAvaliacoes\Readme.md
  
  - Introdução ao BIM: BIM_intro\bim_intro.md

  - Revit:
      - Instalação do Revit: revit\init_revit\instala.md
      - Interface:  revit\init_revit\interface.md
      - Configurações iniciais:  revit\config_init\configura.md
      - Níveis e eixos:  revit\init_revit\ll_gr.md
      - Elementos construtivos:
        - Paredes:  revit\elementos_constructivos\paredes.md
        - Pisos:  revit\elementos_constructivos\pisos.md
        - Portas e janelas:  revit\elementos_constructivos\esquadrias.md
        - Cobertura:  revit\elementos_constructivos\cobertura.md
        - Escadas:  revit\elementos_constructivos\escadas.md
        - Rampas:  revit\elementos_constructivos\rampas.md
        - Pilares:  revit\elementos_constructivos\pilares.md
        - Fundações:  revit\elementos_constructivos\fundacoes.md
        - Vigas:  revit\elementos_constructivos\vigas.md
        - Treliças:  revit\elementos_constructivos\trelicas.md
      - Massa e Terreno:
        - Terrenos:  revit\massa_e_terreno\terrenos.md
        - Plataforma e construção:  revit\massa_e_terreno\bpads.md
        - Modelagem de massas:  revit\massa_e_terreno\massa.md
        - inserção de massas:  revit\EstudoDeMassas-e01\Readme.md
      - Editor de famílias:
        - Criando famílias de pilares:  revit\editorfamilias\familiasPilares.md
      - Representação:
        - Dimensões e cotas:  revit\Anotacoes\cotas.md
        - Norte:  revit\Anotacoes\norte.md
        - Textos:  revit\representacao\representa.md
        - Hierarquia de linhas:  revit\representacao\representa.md
        - Hachura de piso e parede:  revit\representacao\representa.md
        - Quadro de áreas:  revit\representacao\representa.md 
        - Tabelas de quatitativo:  revit\representacao\representa.md
        - Impressão:  revit\representacao\representa.md
        - Estudos de sombra:  revit\representacao\representa.md
        - Render:  revit\representacao\representa.md
      - Links e downloads:
        - Links:  revit\links\links.md
        - downloads:  revit\downloads_revit\downloads.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope-square
        link: mailto:ffribeiro@gmail.com
        