site_name: Introdução ao Revit
use_directory_urls: false

copyright: Copyright &copy; 2016 - 2021 Fernando Ferraz Ribeiro

theme:
  features:

    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  

site_url: "https://255ribeiro.github.io/intro_Revit/"
repo_url: "https://github.com/255ribeiro/intro_Revit/"
repo_name: "255ribeiro/intro_Revit" 


nav:
  - Home: index.md
  # - Editais das Avaliações: revit\EditaisDasAvaliacoes\Readme.md
  
  - Introdução ao BIM: BIM_intro\bim_intro.md
  - Níveis e maturidade do BIM: BIM_intro\levels_mat.md

  - Revit:
      - Instalação do Revit: revit\init_revit\instala.md
      - Interface:  revit\init_revit\interface.md
      - Configurações iniciais:  revit\config_init\configura.md
      - Hierarquia: revit\cat_fam\hierarquia.md
      - Níveis e eixos:  revit\init_revit\ll_gr.md
      - Elementos construtivos:
        - Paredes:  revit\elementos_construtivos\paredes\paredes.md
        - Pisos:  revit\elementos_construtivos\pisos\pisos.md
        - Portas e janelas:  revit\elementos_construtivos\esquadrias\esquadrias.md
        - Cobertura:  revit\elementos_construtivos\cobertura\cobertura.md
        - Escadas:  revit\elementos_construtivos\escadas\escadas.md
        - Rampas:  revit\elementos_construtivos\rampas\rampas.md
        - Guarda-corpo: revit\elementos_construtivos\guarda_corpo\guarda_corpo.md
        - Pilares:  revit\elementos_construtivos\pilares\pilares.md
        - Fundações:  revit\elementos_construtivos\fundacoes\fundacoes.md
        - Vigas:  revit\elementos_construtivos\vigas\vigas.md
        - Treliças:  revit\elementos_construtivos\trelicas\trelicas.md
      - Massa e Terreno:
        - Terrenos:  revit\massa_e_terreno\terrenos.md
        - Plataforma e construção:  revit\massa_e_terreno\bpads.md
        - Modelagem de massas:  revit\massa_e_terreno\massa.md
        - inserção de massas:  revit\EstudoDeMassas-e01\Readme.md
      - Editor de famílias:
        - Criando famílias de pilares:  revit\editorfamilias\familiasPilares.md
      - Representação:
        - Dimensões:  revit\Anotacoes\dim.md
        - Cotas de nivel: revit\Anotacoes\cota_nivel.md
        - Norte:  revit\Anotacoes\norte.md
        - Textos:  revit\representacao\representa.md
        - Hierarquia de linhas:  revit\representacao\h_linhas\h_linhas.md
        - Modelos de Vista:  revit\representacao\modelos_de_vista\modelos_de_vista.md
        - identificadores: revit\tags\tags.md
        - Hachura de piso e parede:  revit\representacao\representa.md
        - Quadro de áreas:  revit\representacao\representa.md
        - Mapas e Detalhes: revit\map_det\map_det.md
        - Tabelas de quatitativo:  revit\representacao\representa.md
        - Impressão:  revit\impress\impress.md
        - Estudos de sombra:  revit\representacao\representa.md
        - Render:  revit\representacao\representa.md
      - Dados:
        - Organizando as pastas do projeto: revit\DADOS\projeto_revit\projeto.md
        - Informações do Projeto: revit\DADOS\project_info.md
        - Planilhas: revit\DADOS\planilhas\planilhas.md
        - Tipos de parâmetros: revit\DADOS\parametros.md
        - Parâmetros de familia: revit\DADOS\param_de_familia.md
        - Parâmetros compartilhados: revit\DADOS\shared_param\shared_param.md
        - IFC:
          - Atualizar exportador IFC do Revit: revit\DADOS\IFC\revit_IFC_install.md
          - Dados do projeto: revit/DADOS/IFC/ifc_project_data.md
      - Georreferenciamento: revit/DADOS/georref/georref.md

      - Links e downloads:
        - Links:  revit\links\links.md
        - downloads:  revit\downloads_revit\downloads.md
      - Extra:
        - Vinculos Cad: revit\vinculosCad\vinc_cad_revit.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope
        link: mailto:fernando.ribeiro@ufba.br
        