site_name: Introdução ao Revit
theme:
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  

site_url: "https://255ribeiro.github.io/Intro_Revit/"
repo_url: "https://github.com/255ribeiro/Intro_Revit/"
repo_name: "255ribeiro/Intro_Revit" 

nav:
  - Home: index.md
  - Editais das Avaliações: EditaisDasAvaliacoes\Readme.md
  
  - Introdução ao BIM: BIM_intro\bim_intro.md

  - Revit:
      - Instalação do Revit: init_revit\instala.md
      - Interface: init_revit\interface.md
      - Configurações iniciais: init_revit\configura.md
      - Níveis e eixos: init_revit\ll_gr.md
      - Elementos construtivos básicos:
        - Paredes: elementos_constructivos\paredes.md
        - pisos: elementos_constructivos\pisos.md
        - Portas e janelas: elementos_constructivos\esquadrias.md
        - Cobertura: elementos_constructivos\cobertura.md
        - Escadas: elementos_constructivos\escadas.md
        - Rampas: elementos_constructivos\rampas.md
        - Pilares: elementos_constructivos\pilares.md
        - Fundações: elementos_constructivos\fundacoes.md
        - Vigas: elementos_constructivos\vigas.md
        - Treliças: elementos_constructivos\trelicas.md
      - Massa e Terreno:
        - Terrenos: massa_e_terreno\terrenos.md
        - Modelagem de massas: massa_e_terreno\massa.md
      - Editor de famílias:
        - Criando famílias de pilares: editorfamilias/familiasPilares.md
      - Representação:
        - Dimensões e cotas: representacao\representa.md
        - Textos: representacao\representa.md
        - Hierarquia de linhas: representacao\representa.md
        - Hachura de piso e parede: representacao\representa.md
        - Quadro de áreas: representacao\representa.md 
        - Tabelas de quatitativo: representacao\representa.md
        - Impressão: representacao\representa.md
        - Estudos de sombra: representacao\representa.md
        - Render: representacao\representa.md
      - Links e downloads:
        - Links: representacao\representa.md
        - downloads: representacao\representa.md


markdown_extensions:
  - toc:
      toc_depth: 3

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter