[tool.poetry]
name = "intro_revit"
version = "0.1.0"
description = "Apresentação ao Revit"
authors = ["Fernando Ferraz Ribeiro <ffribeiro@gmai.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"




[tool.poetry.dev-dependencies]
pymdown-extensions = "^8.2"
mkdocs = "^1.2.2"
mkdocs-multilang = "^0.1.3"
mkdocs-material = "^7.1.11"
mkdocs-jupyter = "^0.17.3"
Markdown = "^3.3.4"
Pygments = "^2.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
