[tool.poetry]
name = "intro_revit"
version = "0.1.0"
description = "Apresentação ao Revit"
authors = ["Fernando Ferraz Ribeiro <ffribeiro@gmai.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pymdown-extensions = "^9.0"
mkdocs = "^1.2.3"
mkdocs-multilang = "^0.1.3"
mkdocs-material = "^8.0.0"
mkdocs-jupyter = "^0.21.0"
Markdown = "^3.4.1"
Pygments = "^2.10.0"


[build-system]
requires = ["poetry-core>=1.1.14"]
build-backend = "poetry.core.masonry.api"
